### ISSUE TITLE
Vex requires jQuery as a dependancy

### ISSUE THREAD

**Issue by hausofwong** [davidyezsetz/you-might-not-need-jquery-plugins#12]
Why is Vex is on here? It requires jQuery as a dependancy:
http://github.hubspot.com/vex/

Or am I missing something?

**Comment by davidyezsetz** [comment]
No, I did apparently. No idea how I overlooked this one. Will remove it asap. Thanks

**Comment by davidyezsetz** [comment]
Removed in: 9582b3e57f3c073ef8ddeb614dfb1d6de40d91bb
