### ISSUE TITLE
Add FitText

### ISSUE THREAD

**Issue by plfstr** [davidyezsetz/you-might-not-need-jquery-plugins#17]
Plain JS implementation by @adactio - https://github.com/adactio/FitText.js

**Comment by davidyezsetz** [comment]
Nice. Didn't knew someone forked it and removed the dependency. Thanks @plfstr

**Comment by davidyezsetz** [comment]
Closed in 6bf53cbcc9c3ab51366c496c7ad9d1cd16a02af9
